# Generated by Django 2.2.6 on 2019-11-18 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250, null=True)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('potential_start_date', models.DateTimeField()),
                ('potential_end_date', models.DateTimeField()),
                ('final_start_date', models.DateTimeField(blank=True, null=True)),
                ('final_end_date', models.DateTimeField(blank=True, null=True)),
                ('admins', models.ManyToManyField(related_name='event_admins', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='event_members', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.CharField(max_length=50000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.CharField(max_length=50000)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
