# Generated by Django 2.2.6 on 2019-10-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='id',
        ),
        migrations.AddField(
            model_name='event',
            name='event_id',
            field=models.CharField(default=123123, max_length=32, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
