# Generated by Django 2.2.6 on 2019-11-16 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191116_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='availability',
            field=models.CharField(max_length=50000),
        ),
    ]
