# Generated by Django 2.2.6 on 2019-11-16 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191116_0117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='finalEndDate',
            new_name='final_end_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='finalStartDate',
            new_name='final_start_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='potentialEndDate',
            new_name='potential_end_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='potentialStartDate',
            new_name='potential_start_date',
        ),
    ]
