# Generated by Django 2.2.6 on 2019-11-23 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191121_2246'),
        ('core', '0004_auto_20191120_1553'),
    ]

    operations = [
    ]
