# Generated by Django 2.2.6 on 2019-10-26 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191026_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.CharField(max_length=1500)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='finalEndDate',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='finalStartDate',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='potentialEndDate',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='potentialStartDate',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='LinkUpUser',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
                ('predefinedSchedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Availability')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='admins',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='event_admins', to='core.LinkUpUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='members',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='event_members', to='core.LinkUpUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='event_owner', to='core.LinkUpUser'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('availability_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Availability')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.LinkUpUser')),
            ],
            bases=('core.availability',),
        ),
    ]
