# Generated by Django 2.2.6 on 2019-10-27 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191026_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='admins',
        ),
        migrations.AddField(
            model_name='event',
            name='admins',
            field=models.ManyToManyField(related_name='event_admins', to='core.LinkUpUser'),
        ),
        migrations.AlterField(
            model_name='event',
            name='finalEndDate',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='finalStartDate',
            field=models.DateTimeField(blank=True),
        ),
        migrations.RemoveField(
            model_name='event',
            name='members',
        ),
        migrations.AddField(
            model_name='event',
            name='members',
            field=models.ManyToManyField(related_name='event_members', to='core.LinkUpUser'),
        ),
        migrations.AlterField(
            model_name='linkupuser',
            name='predefinedSchedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Availability'),
        ),
    ]
