# Generated by Django 2.2.6 on 2019-11-17 16:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191116_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='admins',
            field=models.ManyToManyField(null=True, related_name='event_admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='members',
            field=models.ManyToManyField(null=True, related_name='event_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
