# Generated by Django 2.2.6 on 2019-11-23 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191123_2254'),
        ('core', '0006_auto_20191123_2156'),
    ]

    operations = [
    ]
