# Generated by Django 2.1.11 on 2019-11-23 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191123_2323'),
        ('core', '0006_auto_20191123_2156'),
        ('core', '0006_auto_20191123_2254'),
    ]

    operations = [
    ]
