# Generated by Django 2.2.6 on 2019-10-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191027_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='finalEndDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='finalStartDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
