# Generated by Django 2.1.11 on 2019-11-24 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_merge_20191123_2333'),
        ('core', '0007_merge_20191123_2332'),
    ]

    operations = [
    ]
