# Generated by Django 2.2.6 on 2019-11-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191117_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='potential_end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='potential_start_date',
            field=models.DateTimeField(),
        ),
    ]
