# Generated by Django 2.2.6 on 2019-11-14 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191029_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSchedule',
            fields=[
                ('schedule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Schedule')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Event')),
            ],
            bases=('core.schedule',),
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='availability_ptr',
        ),
        migrations.AddField(
            model_name='schedule',
            name='availability',
            field=models.CharField(default='', max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='id',
            field=models.AutoField(auto_created=True, default='', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
