# Generated by Django 2.2.6 on 2019-11-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_merge_20191124_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.CharField(max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
