# Generated by Django 2.2.6 on 2019-11-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191124_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='no_earlier_than',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='event',
            name='no_later_than',
            field=models.TimeField(auto_now=True),
        ),
    ]
