# Generated by Django 2.2.6 on 2019-11-25 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191124_1941'),
        ('core', '0007_merge_20191123_2335'),
    ]

    operations = [
    ]
