# Generated by Django 2.2.6 on 2019-11-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20191126_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='no_earlier_than',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='no_later_than',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
