# Generated by Django 2.2.6 on 2019-11-27 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20191126_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='no_earlier_than',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='no_later_than',
            field=models.TimeField(),
        ),
    ]
