# Generated by Django 2.2.6 on 2019-11-27 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20191127_0057'),
        ('core', '0010_merge_20191125_1718'),
    ]

    operations = [
    ]
